[package]
name = "client-guide"
version = "0.1.0"
authors = ["Noah Crowley <nsc@noahcrowley.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algorithmia = "3.0.0-beta.3"
serde = "1.0.123"
serde_json = "1.0.61"